### ISSUE TITLE
Fails validation when using global parameters

### ISSUE THREAD

**Issue by KevinMooreNHS** [Azure/data-factory-export-action#1]
This GitHub Action fails when global parameters are referenced from within a pipeline. The validation step of the action doesn't seem to be able to find the global parameter anywhere. In failing validation, no ARM templates are generated.

**Comment by joanteixi** [comment]
Hi! any news on this? Thanks!

**Comment by KevinMooreNHS** [comment]
Not sure.

I see there's been some releases in this space but have yet to rebuild or test anything.

Cheers,
Kevin

**Comment by joanteixi** [comment]
no changes about this issue in the last version published in NPM (1.0.0) same problem happens...

**Comment by Whowong** [comment]
I was running into the same issue and got it to work in the end.  It seems that the ID is not optional if you are using global parameters, adding in my source ADF ID resolved this issue.

**Comment by joanteixi** [comment]
hi @Whowong, could you explain what do you mean with "the ID is not optional"? 

Thanks!

**Comment by Whowong** [comment]
@joanteixi 

Below is an excerpt from the readme:

```
Inputs
path (optional): Directory that contains all Data Factory resources. Defaults to ./ directory.

id (optional): Data Factory resource ID. Defaults to /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/resourceGroup/providers/Microsoft.DataFactory/factories/dataFactory.
```

It mentioned that the ID is optional which seems to be true for many things.  However, it seems to need the DataFactory Resource ID when the global parameters are involved (my hunch based on my tests).  I was able to get this to work once I included my dev environment Data Factory ID.

This is how I am using it in my pipeline:

      - name: Export ARM Template
        id: export
        uses: Azure/data-factory-export-action@v1.0.2
        with:
          id: ${{ secrets.ADFDevResourceID }}

**Comment by joanteixi** [comment]
Hi @Whowong, 

thanks for your answer, but unfortunately I'm using Azure Devops to deploy it, and the ID is always present calling the script. 
And I was not aware that this repo is about the guthub action! in the devops azure version happens something similar!


Thanks!
