### ISSUE TITLE
Archival of deploy action

### ISSUE THREAD

**Issue by davhel** [Azure/data-factory-export-action#7]
Hi there, 

can somebody comment on the archival of the connected github deployment action https://github.com/Azure/data-factory-deploy-action? Is there a planned alternative to the current suggested workflow? 

→ https://learn.microsoft.com/en-us/azure/data-factory/continuous-integration-delivery#script

Thanks for any insight!

**Comment by fedeoliv** [comment]
Hi @davhel 👋,

Please check the [archival notice](https://github.com/Azure/data-factory-export-action?tab=readme-ov-file#️-important-notice) for more details on alternative suggestions. Thank you for your understanding!
